mysite/login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('', views.loginUser, name='login'),
    path('create_account', views.createAccount, name='create_account'),
    path('logout', views.logoutUser, name='logout'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path


"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('', include('risk.urls')),
    path('risk/', include('risk.urls')),
    path('login/', include('login.urls')),
    path('admin/', admin.site.urls),
]

mysite/risk/urls.py
from django.urls import path
from . import views

app_name = "risk"

urlpatterns = [
    path('', views.index, name='index'),
    path('create',views.create,name='create'),
    path('position_create',views.position_create,name='position_create'),
    path('security_create',views.security_create,name='security_create'),
    path('get_hist_data/<str:fund_name>/',views.get_hist_data,name='get_hist_data'),
    path('fund_positions/<str:fund_name>/',views.fund_positions,name='fund_positions'),
    path('get_hist_data_REST',views.get_hist_data_REST,name='get_hist_data_REST'),
]

mysite/risk/models.py
from django.db import models


class Security(models.Model):
    name = models.CharField(max_length=200)
    ticker = models.CharField(max_length=200)
    sector = models.CharField(max_length=200)
    industry = models.CharField(max_length=200)
    asset_class = models.CharField(max_length=200)
    currency = models.CharField(max_length=200)

    def __str__(self):
        return self.ticker


class Fund(models.Model):
    name = models.CharField(max_length=200)
    currency = models.CharField(max_length=3)

    def __str__(self):
        return self.name


class Position(models.Model):
    quantity = models.FloatField()
    last_price = models.FloatField()
    price_date = models.DateField()
    security = models.ForeignKey(Security, on_delete=models.CASCADE)
    fund = models.ForeignKey(Fund, on_delete=models.CASCADE)

    def __str__(self):
        return self.security.ticker

mysite/risk/forms.py
from django import forms
from django.forms import CharField, Textarea

from .models import Fund, Position, Security


# creating a form
class FundForm(forms.ModelForm):

    class Meta:
        # specify model to be used
        model = Fund

        # specify fields to be used
        fields = "__all__"


# creating a form
class PositionForm(forms.ModelForm):

    class Meta:
        # specify model to be used
        model = Position

        # specify fields to be used
        #fields = "__all__"
        fields = ['quantity', 'security', 'fund']

        #field_classes = {'security': forms.CharField}
        widgets = {'security': forms.TextInput}

# creating a form
class SecurityForm(forms.ModelForm):

    class Meta:
        # specify model to be used
        model = Security

        # specify fields to be used
        fields = "__all__"
        #readonly_fields = ['last_price',]

mysite/risk/views.py
from django.shortcuts import render, redirect
import yfinance as yf
import pandas as pd
from .forms import FundForm, PositionForm, SecurityForm
from .models import Security, Position, Fund
from rest_framework.response import Response
from rest_framework.decorators import api_view
from .serializers import FundSerializer
from .risk_functions import get_yf_data, calc_liquidity, calc_performance
from datetime import datetime


def index(request):
    fund_list = Fund.objects.all()
    context = {'fund_list': fund_list, 'user': str(request.user)}
    return render(request, 'risk/index.html', context)


def create(request):
    context = {}

    form = FundForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('risk:index')

    context['form'] = form
    return render(request, "risk/create.html", context)


def position_create(request):
    context = {}

    # make a copy of the post request so it can be altered
    updated_request = request.POST.copy()
    securities = Security.objects.all()
    form = PositionForm(updated_request or None, initial={'quantity': 6667})
    form.fields['fund'].initial = 'ABC UCITS'
    ticker = form['security'].value()

    if request.method == 'POST':

        ticker_list = list((securities.values_list('ticker', flat=True)))

        # If the ticker entered in the form is already an existing Security then change the ticker
        # in the form to the index of the Security in the Security list so the form references
        # a Security object rather than a string. Else set the form value to '0'.
        if ticker in ticker_list:
            updated_request.update({'security': str(ticker_list.index(ticker) + 1)})
        else:
            updated_request.update({'security': '0'})

        # Create Security if doesn't exist
        if int(form['security'].value()) == 0:

            yf_ticker = yf.Ticker(ticker)
            ticker_info = yf_ticker.info

            # check if ticker is valid
            if len(ticker_info) > 3:
                security = Security.objects.create(
                    name=ticker_info['longName'], ticker=ticker, 
                    sector=ticker_info['sector'],industry=ticker_info['industry'],
                    asset_class=ticker_info['quoteType'], currency=ticker_info['currency'])
                    
                ticker_list = list((securities.values_list('ticker', flat=True)))
                updated_request.update({'security': str(ticker_list.index(ticker) + 1)})

        if form.is_valid():
            instance = form.save(commit=False)
            closing_price = yf.Ticker(ticker).history(period="1d")['Close']
            closing_price.index = closing_price.index.strftime('%Y/%m/%d')
            instance.last_price = closing_price.item()
            instance.price_date = datetime.strptime(closing_price.index[0],'%Y/%m/%d')
            form.save()
            return redirect('risk:index')

    context['form'] = form

    return render(request, "risk/position_create.html", context)


def security_create(request):
    context = {}

    form = SecurityForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('risk:index')

    context['form'] = form
    return render(request, "risk/security_create.html", context)


def fund_positions(request, fund_name):
    print(fund_name)
    positions = Position.objects.filter(fund__name=fund_name)
    context = {'fund_positions': positions}
    print(context)
    #print(request.session[fund_name])
    return render(request, "risk/fund_positions.html", context)


@api_view(['GET'])
def get_hist_data_REST(request):
    #print(fund_name)
    #positions = Position.objects.filter(fund__name=fund_name)
    # fund = Fund.objects.filter(name=fund_name)
    # print(fund[0].Positions.all())
    #ticker_string = ''
    #for position in positions:
    #    print(position)
    #    ticker_string = ticker_string + str(position) + ' '

    request.session.set_expiry(0)
    #print('Ticker String')
    #print(ticker_string)
    #yf_data = get_yf_data(ticker_string)
    #print(yf_data)
    #request.session[fund_name] = yf_data.to_json(orient="split")
    # request.session['fav_color'] = 'blue'
    # print(request.session['fav_color'])
    #print(request.session[fund_name])
    #context = {'hist_data': request.session[fund_name]}
    # return render(request, "risk/get_hist_data.html", context)

    funds = Fund.objects.all()
    serializer = FundSerializer(funds, many=True)
    return Response(serializer.data)

    #return Response(context)

def get_hist_data(request, fund_name):
    positions = Position.objects.filter(fund__name=fund_name)
    print(list(positions.values_list('security_id','quantity')))
    #print(list(positions.values_list('quantity', flat=True))) 
    if positions.count() > 0:
        ticker_string = ''
        position_dict = {}

        for position in positions:
            position_dict[str(position)] = [position.quantity]
            ticker_string = ticker_string + str(position) + ' '

        request.session.set_expiry(0)

        yf_data = get_yf_data(ticker_string)
        yf_data.index = yf_data.index.strftime('%Y-%m-%d')

        performance = calc_performance(yf_data['Close'])
        print(performance)

        average_volumne = yf_data['Volume'].reset_index().mean().to_dict()
        
        for position in positions:
            ticker_series = yf_data['Close'][str(position)]
            last_price_index = ticker_series.last_valid_index()
            last_price_loc = ticker_series.index.get_loc(last_price_index)
            position.last_price = ticker_series[last_price_loc]
            position.price_date = datetime.strptime(last_price_index,'%Y-%m-%d')
            position.save()

        for ticker in average_volumne:
            if positions.count() > 1:
                position_dict[ticker].append(average_volumne[ticker])
            else:
                position_dict[ticker_string.strip()].append(average_volumne[ticker])

        liquidity_dict = {}
        for ticker in position_dict:
            quantity = float(position_dict[ticker][0])
            adv = float(position_dict[ticker][1])
            liquidity_dict[ticker] = calc_liquidity(quantity,adv) 
        
        context = {'hist_data': liquidity_dict}

        #request.session[fund_name] = '{"closing":' + yf_data['Close'].to_json(orient="split") +\
        #', "volume":' + yf_data['Volume'].to_json(orient="split") + '}'

        return render(request, "risk/get_hist_data.html", context)

    else:
        return redirect('risk:index')

mysite/risk/templates/risk/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="POST" enctype="multipart/form-data">

        <!-- Security token -->
        {% csrf_token %}

        <!-- Using the formset -->
        {{ form.as_p }}

        <input type="submit" value="Submit">
    </form>
</body>
</html>

mysite/risk/templates/risk/fund_positions.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <a href="{% url 'risk:position_create' %}">Add Position</a>

    {% if fund_positions %}
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Ticker</th>
                <th>Currency</th>
                <th>Quantity</th>
                <th>Last Price</th>
                <th>Price Date</th>
                <th>Industry</th>
                <th>Sector</th>
                <th>Asset Class</th>

            </tr>
        </thead>

        <tbody>
        {% for position in fund_positions %}
            <tr>
                <td>{{position.security.name}}</td>
                <td>{{position}}</td>
                <td>{{position.security.currency}}</td>
                <td>{{position.quantity}}</td>
                <td>{{position.last_price}}</td>
                <td>{{position.price_date}}</td>
                <td>{{position.security.sector}}</td>
                <td>{{position.security.industry}}</td>
                <td>{{position.security.asset_class}}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
        <p>No Positions</p>
    {% endif %}
</body>
</html>

mysite/risk/templates/risk/get_hist_data.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Title</title>
</head>
<body>
    {{hist_data}}
</body>
</html>

mysite/risk/templates/risk/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if user == 'AnonymousUser'%}
        <span><a href="{% url 'login:login' %}">Login</a></span>
    {% else %}
        <span><a href="{% url 'login:logout' %}">Logout ({{user}})</a></span>
    {% endif %}
    <a href="create">Add Fund</a>
    <a href="position_create">Add Position</a>
    <a href="security_create">Add Security</a>

    {% if fund_list %}
    <table>
        <thead>
            <tr>
                <th>Fund name</th>
                <th>Currency</th>
            </tr>
        </thead>

        <tbody>
        {% for fund in fund_list %}
            <tr>
                <td>{{fund.name}}</td>
                <td>{{fund.currency}}</td>
                 <td><a href="{% url 'risk:get_hist_data' fund.name %}">Run</a></td>
                <td><a href="{% url 'risk:fund_positions' fund.name %}">Portfolio</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
        <p>No Funds</p>
    {% endif %}

</body>
</html>

mysite/risk/templates/risk/position_create.html
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="POST" enctype="multipart/form-data">

        <!-- Security token -->
        {% csrf_token %}

        <!-- Using the formset -->
        {{ form.as_p }}

        <input type="submit" value="Submit">
    </form>
</body>
</html>

mysite/risk/templates/risk/security_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="POST" enctype="multipart/form-data">

        <!-- Security token -->
        {% csrf_token %}

        <!-- Using the formset -->
        {{ form.as_p }}

        <input type="submit" value="Submit">
    </form>
</body>
</html>