mysite/login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('', views.loginUser, name='login'),
    path('create_account', views.createAccount, name='create_account'),
    path('logout', views.logoutUser, name='logout'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path


"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('', include('risk.urls')),
    path('risk/', include('risk.urls')),
    path('login/', include('login.urls')),
    path('admin/', admin.site.urls),
]

mysite/risk/urls.py
from django.urls import path
from . import views

app_name = "risk"

urlpatterns = [
    path('', views.index, name='index'),
    path('create',views.create,name='create'),
    path('position_create',views.position_create,name='position_create'),
    path('security_create',views.security_create,name='security_create'),
    path('get_hist_data/<str:fund_name>/',views.get_hist_data,name='get_hist_data'),
    path('fund_positions/<str:fund_name>/',views.fund_positions,name='fund_positions'),
    path('get_hist_data_REST',views.get_hist_data_REST,name='get_hist_data_REST'),
]

mysite/login/models.py
from django.db import models

# Create your models here.

mysite/login/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class LoginForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']

mysite/login/views.py
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import LoginForm


# Create your views here.

def createAccount(request):
    form = UserCreationForm()

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login:login')

    context = {'form': form}
    return render(request, 'login/create_account.html', context)


def loginUser(request):
    context = {}
    form = LoginForm(request.POST)

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username,password=password)

        if user is not None:
            login(request, user)
            return redirect('risk:index')
        else:
            messages.info(request, 'Username OR password is incorrect')

    context['form'] = form

    return render(request, 'login/login_page.html', context)

def logoutUser(request):
    logout(request)
    return redirect('risk:index')

mysite/login/templates/login/create_account.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <form method="POST",action="">
        {% csrf_token %}
        {{form.username.label}}
        {{form.username}}

        {{form.password1.label}}
        {{form.password1}}

        {{form.password2.label}}
        {{form.password2}}

        {{form.errors}}
        <input type="submit" name="create_user">
    </form>
    Helloooooo2
</body>
</html>

mysite/login/templates/login/login_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="POST" enctype="multipart/form-data">

        {% csrf_token %}

        {{form.username.label}}
        {{form.username}}

        {{form.password.label}}
        {{form.password}}

        <input type="submit" value="Submit">
    </form>

    {% for message in messages %}
        <p id="messages">{{message}}</p>
    {% endfor %}

    <a href="{% url 'login:create_account' %}">Create Account</a>

</body>
</html>